[dependencies]
"ystyle::zip" = "1.0.5"
"cjpminfo" = "1.2.0"

[package]
  name = "cjvs"
  description = "仓颉编译器版本切换工具"
  version = "0.3.8"
  cjc-version = "1.1.0"
  compile-option = "--static -Woff driver-arg -Woff unused"
  link-option = ""
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  include =["src"]
  license = ["MIT"]
  authors = ["ystyle"]
  repository = "https://atomgit.com/OpenCangjieCommunity/cjvs"
  package-configuration = {}

[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_PATH}"]
[target.aarch64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_PATH}"]
[target.x86_64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_PATH}"]
[target.aarch64-apple-darwin.bin-dependencies]
  path-option = ["${CANGJIE_STDX_PATH}"]
[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX_PATH}"]

[profile.build]
incremental = true
